name: ScreenShotTest
on:
  pull_request:

jobs:
  screenshot-test:
    runs-on: macos-12
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Download Screenshots
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: UpdateScreenshots.yml
          name: screenshots
          path: preview-screenshots/src/test/snapshots/images

      - name: Run screenshot tests
        id: verifyPaparazziDebug
        continue-on-error: true
        run: ./gradlew preview-screenshots:verifyPaparazziDebug

      - name: Error Screenshot tests
        if: ${{ hashFiles('preview-screenshots/out/failures/*.png') != '' }}
        uses: actions/upload-artifact@v3
        with:
          name: screenshot-test-results
          path: preview-screenshots/out/failures

      - name: Checkout the companion branch
        id: checkout_docs
        if: ${{ hashFiles('preview-screenshots/out/failures/*.png') != '' }}
        uses: actions/checkout@v3
        with:
          path: temp_docs

      - name: Commit the screenshot to the branch
        id: docs_images
        if: steps.checkout_docs.outcome == 'success'
        continue-on-error: true # https://github.com/DroidKaigi/conference-app-2022/issues/497
        env:
          BRANCH_NAME: companion_${{ github.head_ref || github.ref_name }}
        run: |
          cd temp_docs/
          git switch -C $BRANCH_NAME
          mkdir -p docs/screenshots/
          cp -a ../preview-screenshots/out/failures/. docs/screenshots/
          git add .
          git config --global push.default current
          git config --global remote.pushDefault origin
          git commit -m "Upload screenshots to github page."
          git push -f
          cd ..
          cd preview-screenshots/out/failures
          echo ::set-output name=images::$(ls -d delta* | jq -R -s -c 'split("\n")[:-1]' | jq -r --arg IMAGE_PATH "https://raw.githubusercontent.com/eneim/conference-app-2022/$BRANCH_NAME/docs/screenshots/" '.[] |= $IMAGE_PATH + .')

      - name: Build PR Comment with Preview
        id: pr_comment
        if: steps.docs_images.outcome == 'success'
        # if: ${{ hashFiles('preview-screenshots/out/failures/*.png') != '' }}
        continue-on-error: true # https://github.com/DroidKaigi/conference-app-2022/issues/497
        env:
          ALL_SCREENSHOTS: ${{ steps.docs_images.outputs.images }}
        # Build a comment message with the image from snapshot images for demo purpose.
        run: |
          echo "There are differences in Compose previews:" > report.md
          echo >> report.md # A blank line.
          echo "$ALL_SCREENSHOTS" | jq -r '.[]' | while read -r image; do 
            echo "![]($image)" >> report.md
          done
          echo ::set-output name=comment::$(cat report.md)

      - name: Comment PR
        # if: ${{ hashFiles('preview-screenshots/out/failures/*.png') != '' }}
        if: steps.pr_comment.outcome == 'success'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: ${{ steps.pr_comment.outputs.comment }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
